description: Stack para a criacao de script em python para envio de payload para flias aws sqs
name: hands-on-py-publisher-awssqs
display-name: hands-on-py-publisher-awssqs
picture: stack.png
category: backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility: # Put a list of technologies compatible with the stack
  - python
  - sqs
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
about: docs/about.md
use-cases:
  - title: Use Case Title
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml